project7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('story7/', include(('story7.urls', 'story7'), namespace='story7'))
]

story7/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url 
from .views import index as landingpage
from .views import profilepage

urlpatterns = [
    path('', landingpage, name='landing-page'),
    path('status', landingpage, name='landing-page'),
	path('profile/', profilepage, name='profile')

]

story7/models.py
from django.db import models
from datetime import date

# Create your models here.

class StatusModels(models.Model):
	description = models.CharField(max_length=300)
	date = models.DateField(auto_now_add=True)

story7/forms.py
from django import forms
from datetime import date

class StatusForm(forms.Form):
	attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Curhat disini yuk'
    }
	description = forms.CharField(label='', required=True, max_length=200, widget=forms.Textarea(attrs=attrs))

story7/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.

from .models import StatusModels
from .forms import StatusForm

def index(request):
    hasil = StatusModels.objects.all()
    if request.method == 'POST':
        form = StatusForm(request.POST)
        if form.is_valid():
            description = request.POST['description']
            stat = StatusModels.objects.create(description=description)
            return render(request, 'index.html', {'form': form, 'description': hasil})
    else:
        form = StatusForm()
        return render(request, 'index.html', {'form': form, 'description': hasil})
'''response = {'author' : 'syifa'}

def index(request):
    form = StatusForm(request.POST or None)
    response['status_form'] = form
    # if this is a POST request we need to process the form data
    print(request.method)
    if request.method == 'POST':
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            response['description'] = request.POST['description']

            the_status = StatusModels(description=response['description'])
            the_status.save()

            return HttpResponseRedirect(reverse('appbang:allstatus'))

    # if a GET (or any other method) we'll create a blank form
    else:

        return render(request, 'index.html', response)

    

def allstatus(request):
    all_status = StatusModels.objects.all()
    response['all_status'] = all_status
    return render(request, 'updatestatus.html', response)'''


def profilepage(request):
    return render(request, 'profile.html')

story7/templates/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!--link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css"-->



	<title style="font-family: 'Montserrat'">Story 6 : Bang</title>
	
	<!--meta name="viewport" content="width=device-width, initial-scale=1"-->
	
</head>
<body>
    <div class="container">
    <header style="margin-top: 50px">{% include "navbar.html" %}
        </header>

    <h1 style="margin: auto;">Hello, apa kabar?</h1>


    <div>
        <form action="status" method="post" class="description" >
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                {{ field }}
            </div>
            {% endfor %}
        <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    <div class="card bg-info text-white">
        {% for i in description %}
            <div class="card-body">
            {{ i.date }}<br>
            {{ i.description }}
            </div>
        {% endfor %}
    </div>


    </div>
            
    


</body>
</html>

story7/templates/navbar.html
{% load staticfiles %}
{% load static %}

<div class="topnav" id="nav">
  <a href="{% url 'story7:landing-page' %}">Home</a>
  <a href="{% url 'story7:profile' %}">Profile</a>
</div>

story7/templates/profile.html
{%load static%}

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
    <link href='https://fonts.googleapis.com/css?family=Archivo' rel='stylesheet'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!--link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css"-->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
</head>
<body>
  	<!--Menu!-->
  	<div class="container">
 	<header style="margin-top: 50px">
  		{% include 'navbar.html' %}
	</header>

		<h1>Hola, I'm Syifa</h1>
		<div class="content" style="float: center">
			<p style="float:center">Tulisan ini dibuat untuk mengisi kekosongan web saya di story 6.</p> 
		</div>
	</div>

</body>
</html>

story7/templates/updatestatus.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="{% static 'css/style.css'%}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Archivo' rel='stylesheet'>

</head>
<body>

  <!--Menu!-->
<div class="container">
    <header style="margin-top: 50px">{% include "navbar.html" %}
        </header>

    <h1>Daily Life</h1>


    <div class="row">
      <div class="column">
        <div class="card">
          {% for status in all_status %}
          <h4>{{status.date}}</h4>
          <p>{{status.description}}</p>
          {% endfor %}
        </div>
      </div>
    </div>

</div>
</body>
</html>